/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/scenes/projects/models/NewRoom.glb --transform 
Files: src/scenes/projects/models/NewRoom.glb [19.31MB] > D:\Projects\2024_Portfolio\NewRoom-transformed.glb [1.94MB] (90%)
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import room from "./NewRoom-transformed.glb";

export default function NewRoom(props) {
  const { nodes, materials } = useGLTF(room);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WallRoof.geometry}
        material={materials.PaletteMaterial001}
        position={[8.136, 11.048, -4.303]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.PcCase.geometry}
        material={materials.PaletteMaterial003}
        position={[4.555, 5.87, -2.812]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <group
        position={[2.235, 8.736, -4.59]}
        rotation={[Math.PI / 2, 1.046, Math.PI]}
      >
        <mesh
          geometry={nodes.Circle015.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Circle015_1.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Circle015_2.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.PaletteMaterial002}
        position={[4.827, 5.776, -3.321]}
        rotation={[2.927, -1.571, 0]}
      />
      <mesh
        geometry={nodes.PcFanFilter.geometry}
        material={nodes.PcFanFilter.material}
        position={[5.062, 5.822, -1.788]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Gear.geometry}
        material={nodes.Gear.material}
        position={[-8.595, 5.744, -2.626]}
        rotation={[0, -1.567, 0]}
        scale={1.188}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials["Zig-zag grey plastic"]}
        position={[-8.567, 5.739, -2.278]}
        rotation={[0, -1.567, 0]}
        scale={1.188}
      />
      <mesh
        geometry={nodes.Office_Chair_REX.geometry}
        material={materials["Office Chair_Fabric"]}
        position={[-3.387, 1.587, 0.966]}
        rotation={[-Math.PI, -0.574, -Math.PI]}
        scale={5.756}
      />
    </group>
  );
}

useGLTF.preload(room);
